### ISSUE TITLE
Google Translate API doesn't seem to support regional lang codes

### ISSUE THREAD

**Issue by Djive** [enupal/translate#13]
Tried to translate from "en" to "hr-HR" and got error message shown below.
When I tried to translate from "en" to "hr", then its working fine.

2018-10-12 12:36:05 [-][1][-][error][enupal\translate\contracts\GoogleCloudTranslate::translate] Translate error: Client error: `POST https://www.googleapis.com/language/translate/v2?q=Your+name&target=hr-HR&source=en&key=xxxxxxxxxxxxxxxxxxxxxxxxxxxx` resulted in a `400 Bad Request` response:
{
  "error": {
    "code": 400,
    "message": "Invalid Value",
    "errors": [
      {
        "message": "Invalid Valu (truncated...)

2018-10-12 12:36:05 [-][1][-][info][application] $_GET = [
    'p' => 'admin/actions/element-indexes/perform-action'
]

$_POST = [
    'context' => 'index'
    'elementType' => 'enupal\\translate\\elements\\Translate'
    'source' => 'status:pending'
    'criteria' => [
        'status' => ''
        'siteId' => '2'
        'search' => ''
        'limit' => '50'
        'enabledForSite' => ''
    ]
    'viewState' => [
        'mode' => 'table'
        'order' => 'original'
        'sort' => 'asc'
    ]
    'elementAction' => 'enupal\\translate\\elements\\actions\\GoogleCloudTranslate'
    'elementIds' => [
        0 => 'your-name'
    ]
]

- Craft version: 3.0.27
- PHP version: 7.2.6
- Database driver & version: MySQL 5.6.38
- Plugin version: 1.1.3

**Comment by andrelopez** [comment]
Hi @Djive 

This issue is solved in v1.1.4 could you please update the plugin and let us know it is solved?

Best,

**Comment by Djive** [comment]
Craft CMS 3.0.27.1
Enupal Translate 1.1.4

Still getting this error when trying to translate from en to hr-HR (en to hr is working):

2018-10-18 14:23:59 [-][1][-][error][enupal\translate\contracts\GoogleCloudTranslate::translate] Translate error: Client error: `POST https://www.googleapis.com/language/translate/v2?q=Ticket&q=Are+you+sure+you+want+to+delete+the+selected+tickets%3F&q=Tickets+deleted.&q=Title&q=Status&q=Author&q=Date+Created&q=Date+Updated&q=Message&q=No+email+exists+with+the+ID+%22%7Bid%7D%22&q=This+is+being+overridden+by+the+%7Bsetting%7D+config+setting+in+your+%7Bfile%7D+config+file.&q=Allow+Attachments&q=Manage+Tickets&q=Delete+Tickets&target=hr-HR&source=en&key=xxxxxxxxxxxxxxxxxxxx` resulted in a `400 Bad Request` response:
{
  "error": {
    "code": 400,
    "message": "Invalid Value",
    "errors": [
      {
        "message": "Invalid Valu (truncated...)

**Comment by andrelopez** [comment]
Hi @Djive 

Thanks for following up, Could you please update your plugin to v1.1.5 and let me know if the issue is solved?

Best,
