### ISSUE TITLE
Cannot install latest version on Craft 3.6.11.1

### ISSUE THREAD

**Issue by belkin** [enupal/translate#43]
### Description
I'm trying to install Translate plugin on latest Craft 3.6.11.1 but I'm getting the following error:

` Problem 1
    - stichoza/google-translate-php v3.2.15 requires guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.5] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - enupal/translate 2.0.0 requires stichoza/google-translate-php 3.2.15 -> satisfiable by stichoza/google-translate-php[v3.2.15].
    - Root composer.json requires enupal/translate ^2.0 -> satisfiable by enupal/translate[2.0.0].
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

### Steps to reproduce

1. 'composer require enupal/translate' on Craft CMS 3.6.11.1
2.

### Additional info

- Craft version: 3.6.11.1
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7
- Plugin version: latest
- Installed plugins: 
`      "aelvan/imager": "v2.4.0",
        "craftcms/cms": "3.6.11.1",
        "craftcms/redactor": "2.8.5",
        "dgrigg/craft-migration-assistant": "^3.2",
        "fruitstudios/linkit": "1.1.12.1",
        "glue-agency/craft-fingerprint-assets": "^1.0",
        "hybridinteractive/craft-position-fieldtype": "1.0.17",
        "nystudio107/craft-seomatic": "3.3.36",
        "ostark/craft-async-queue": "2.2.0",
        "putyourlightson/craft-sendgrid": "1.2.2",
        "solspace/craft-freeform": "^3.10.11",
        "studioespresso/craft-navigate": "2.7.4",
        "verbb/super-table": "2.6.7",
        "viget/craft-video-embed": "^1.2",
        "vlucas/phpdotenv": "^2.4.0"`

**Comment by jan-dh** [comment]
Any update on this? Not being able to install the plugin is a bit of a pain :)

**Comment by andrelopez** [comment]
hi @belkin we just released Enupal Translate v2.2.0 could update the plugin and try again and let me know if that works?

**Comment by belkin** [comment]
Hey @andrelopez, 

During the installation I still get error but this time is another one: 

`Problem 1
    - enupal/translate 2.2.0 requires viniciusgava/google-translate-api 2.1.0 -> satisfiable by viniciusgava/google-translate-api[2.1.0].
    - Installation request for enupal/translate ^2.2 -> satisfiable by enupal/translate[2.2.0].
    - Conclusion: remove guzzlehttp/guzzle 7.2.0
    - Conclusion: don't install guzzlehttp/guzzle 7.2.0
    - viniciusgava/google-translate-api 2.1.0 requires guzzlehttp/guzzle ^6.3.0 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.2.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0) -> satisfiable by guzzlehttp/guzzle[7.2.0].`

But during the first installation it was fixed through this flag: 
`Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

But now I'm not even getting this message.

**Comment by andrelopez** [comment]
@belkin could you please send me your composer.json file to support@enupal.com?

**Comment by frontedbe** [comment]
Having the same issue when trying to install craftcms/commerce-mollie 
[screenshot](https://share.getcloudapp.com/xQubOpJG)

**Comment by andrelopez** [comment]
@mdominguez I am on it

**Comment by frontedbe** [comment]
@andrelopez Just reaching out if there's any news on this? Thanks man!

**Comment by belkin** [comment]
Sorry for late input but the problem is solved with fresh composer.lock file. So I've just removed .lock file and after that installation was no issue. Apparently it was een issue with dependencies from other third party plugins.

I'm not closing the issue because I see other people still have issues there. But for our situation it's fixed.

**Comment by maxpdesign** [comment]
@andrelopez Some plugins are using Guzzle 7 now instead of Guzzle 6. I see that this plugin requires viniciusgava/google-translate-php-client which uses Guzzle 6. They have an open issue (https://github.com/viniciusgava/google-translate-php-client/issues/14) and PR ready for Guzzle 7. Can you confirm this plugin will work with Guzzle 7?

**Comment by jacotijssen** [comment]
Any news on this?

**Comment by andrelopez** [comment]
Hi we just released Enupal Translate v2.3.0 with a fix to this issue, please let me know how it goes
